#####   BASIC   ######################################
debug: false

wandb_project: kaggle_asl2
dataset_name: data0001
seed: 77
n_epochs: 50
split_method: StratifiedGroupKFold
n_folds: 5
use_fold: [0] # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
save_model: false
use_amp: true
n_valid_per_epoch: 3
batch_max_length: 32

#####   Frame   ######################################
use_types: [left_hand, right_hand, lips]
hand_max_length: 128 # max: 574
lips_max_length: 16 # max: 784
padding: "constant_value" # ['edge', 'constant_value']
padding_value: 0 # padding in ['constant_value']
frame_drop_rate: 0.0

##### DataLoader #####################################
train_bs: 64
valid_bs: 64

#####   Model   ######################################
dim1_H: 128
dim1_L: 64
dim2: 512

restart:
pretrained_model_from_net_path:
pretrained_model_exp_name:

##### Optimizer ######################################
lr: 1e-2
optimizer: AdamW
weight_decay: 1e-6

##### Scheduler ######################################
scheduler: CosineAnnealingWarmRestarts # OneCycleLR, CosineAnnealingWarmRestarts
scheduler_step_frequence: epoch # step, epoch
T_0: ${n_epochs} # CAWR
T_mult: 1 # CAWR
eta_min: 1e-7 # CAWR

pct_start: 0.05 # OCLR
div_factor: 100. # OCLR
final_div_factor: 1000. # OCLR
