#####   BASIC   ######################################
debug: false
use_wandb: false

wandb_project: kaggle_asl2
dataset_name: data0001
seed: 77
n_epochs: 10
split_method: StratifiedGroupKFold
n_folds: 5
use_fold: [0] # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
save_model: false
use_amp: true
n_valid_per_epoch: 3

batch_max_length: 256

#####   Frame   ######################################
use_types: [left_hand, right_hand, lips]
hand_max_length: 574 # max: 574
lips_max_length: 784 # max: 784
padding: "constant_value" # ['edge', 'constant_value']
padding_value: 0 # padding in ['constant_value']
frame_drop_rate: 0.0

#####   Model   ######################################
dim1_H: 128
dim1_L: 64
dim2: 512

restart: true
pretrained_model_from_net_path:
pretrained_model_exp_name:

##### Optimizer ######################################
optimizer: AdamW
lr: 3e-5
weight_decay: 0

##### Scheduler ######################################
scheduler: OneCycleLR # OneCycleLR, huggingface_scheduler
scheduler_step_frequence: step
T_0: ${n_epochs} # CAWR
T_mult: 1 # CAWR
eta_min: 1e-9 # CAWR

pct_start: 0.1 # OCLR
div_factor: 100. # OCLR
final_div_factor: 1000. # OCLR

##### Image Info #####################################
# img_h: 560
# img_w: 560

##### Text Info ######################################
# max_length: 1024
# max_patches: 1024

##### DataLoader #####################################
train_bs: 16
valid_bs: 16
num_workers: 8
